// @flow
export const CREATE_TABLE_BUTTON_CLICK = 'CREATE_TABLE_BUTTON_CLICK';
export const ADD_PLUS_ONE_IN_CELL = 'ADD_PLUS_ONE_IN_CELL';
export const ADD_ROW_TO_TABLE = 'ADD_ROW_TO_TABLE';
export const DELETE_ROW_TO_TABLE = 'DELETE_ROW_TO_TABLE';
export const UPDATE_VALUES_FROM_SERVER = 'UPDATE_VALUES_FROM_SERVER';
